services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine

    restart: unless-stopped

    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pr@jj7878

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: